package it.pagopa.ecommerce.commons.documents.v2.authorization;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

/**
 * Extensible interface to handle multiple payment gateway transaction outcome
 */
@JsonIgnoreProperties(
        value = "type", // ignore manually set detailType, it will be automatically generated by Jackson
        // during serialization
        allowSetters = true // allows the detailType to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type", visible = false)
@JsonSubTypes(
    {
            @JsonSubTypes.Type(value = PgsTransactionGatewayAuthorizationData.class, name = "PGS"),
            @JsonSubTypes.Type(value = NpgTransactionGatewayAuthorizationData.class, name = "NPG"),
            @JsonSubTypes.Type(value = RedirectTransactionGatewayAuthorizationData.class, name = "REDIRECT"),
    }
)
public sealed interface TransactionGatewayAuthorizationData permits NpgTransactionGatewayAuthorizationData,PgsTransactionGatewayAuthorizationData,RedirectTransactionGatewayAuthorizationData {

    /**
     * Authorization data type discriminator field enumeration
     */
    enum AuthorizationDataType {
        /**
         * PGS data type
         */
        PGS,
        /**
         * NPG data type
         */
        NPG,
        /**
         * Redirect data type
         */
        REDIRECT
    }

    /**
     * Get discriminator field enumeration value
     *
     * @return the detail type enumeration value associated to the current detail
     *         instance
     */
    AuthorizationDataType getType();
}
