package it.pagopa.ecommerce.commons.domain.pojos;

import it.pagopa.ecommerce.commons.documents.v1.TransactionRefundedData;
import it.pagopa.ecommerce.commons.documents.v1.TransactionRefundedEvent;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;
import lombok.experimental.FieldDefaults;

/**
 * <p>
 * POJO for a refunded transaction.
 * </p>
 * <p>
 * All accrued data is exposed through the same structure generated by
 * {@link TransactionRefundedEvent TransactionRefundedEvent}, namely
 * {@link TransactionRefundedData TransactionRefundedData}.
 * </p>
 *
 * @see BaseTransaction
 * @see TransactionRefundedEvent
 */
@ToString
@EqualsAndHashCode(callSuper = true)
@FieldDefaults(makeFinal = true, level = AccessLevel.PRIVATE)
@Getter
public abstract class BaseTransactionRefunded extends BaseTransaction {
    TransactionRefundedData transactionRefundedData;
    BaseTransaction transactionAtPreviousState;

    /**
     * Primary constructor
     *
     * @param baseTransaction         base transaction
     * @param transactionRefundedData the transaction refunded data
     */
    protected BaseTransactionRefunded(
            BaseTransaction baseTransaction,
            TransactionRefundedData transactionRefundedData
    ) {
        super(
                baseTransaction.getTransactionId(),
                baseTransaction.getPaymentNotices(),
                baseTransaction.getEmail(),
                baseTransaction.getCreationDate(),
                baseTransaction.getClientId()
        );
        this.transactionRefundedData = transactionRefundedData;
        this.transactionAtPreviousState = baseTransaction;
    }
}
