package it.pagopa.ecommerce.commons.documents.v2.refund;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

/**
 * Common interface for gateway specific information for a refunded transaction
 *
 * @see EmptyGatewayRefundData
 * @see NpgGatewayRefundData
 */
@JsonIgnoreProperties(
        value = "type", // ignore manually set detailType, it will be automatically generated by Jackson
        // during serialization
        allowSetters = true // allows the detailType to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type", visible = false)
@JsonSubTypes(
    {
            @JsonSubTypes.Type(value = NpgGatewayRefundData.class, name = "NPG"),
            @JsonSubTypes.Type(value = EmptyGatewayRefundData.class, name = "EMPTY"),
    }
)
public sealed interface GatewayRefundData permits EmptyGatewayRefundData,NpgGatewayRefundData {
    /**
     * Enumeration of all Gateway refund data types
     */
    enum RefundDataType {
        /**
         * Refunded transaction data for NPG gateway
         */
        NPG,
        /**
         * Empty refund data type: placeholder for gateway that does have not additional
         * information to be saved after a refund operation have been done
         */
        EMPTY
    }

    /**
     * Gateway refund data type
     *
     * @return the gateway refund data type
     */
    RefundDataType getType();
}
