openapi: 3.0.3
info:
  title: Specification for eCommerce transaction status
  description: Specification for eCommerce transaction status
  version: 1.0.0
paths:
  /required-for-openapi-validation:
    get:
      operationId: required-for-openapi-validation
      responses:
        '200':
          description: required-for-openapi-validation
components:
  schemas:
    TransactionStatus:
      type: string
      description: Possible statuses a transaction can be in
      enum:
        - ACTIVATED
        - AUTHORIZATION_REQUESTED
        - AUTHORIZATION_COMPLETED
        - CLOSURE_REQUESTED
        - CLOSED
        - CLOSURE_ERROR
        - NOTIFIED_OK
        - NOTIFIED_KO
        - NOTIFICATION_ERROR
        - NOTIFICATION_REQUESTED
        - EXPIRED
        - REFUNDED
        - CANCELED
        - EXPIRED_NOT_AUTHORIZED
        - UNAUTHORIZED
        - REFUND_ERROR
        - REFUND_REQUESTED
        - CANCELLATION_REQUESTED
        - CANCELLATION_EXPIRED
    AuthorizationResult:
      description: Authorization result
      type: string
      enum:
        - OK
        - KO
