name: Create PR on eCommerce project with version update

on:
  release:
    types:
      - published

permissions:
  pull-requests: write
  packages: write

jobs:
  deploy_artifact:
    if: ${{needs.semver_labels.outputs.skip_release == 'False'}}
    name: Deploy github package
    needs: semver_update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release branch
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 #v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      # this action set up also maven configuring github as server
      - name: Set up JDK 21
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3
        with:
          java-version: '21'
          distribution: 'corretto'
      - name: Cache Maven packages
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Deploy to GitHub Package Registry
        run: |
          REPO="github::https://maven.pkg.github.com/pagopa/pagopa-ecommerce-commons"
          mvn deploy -DaltReleaseDeploymentRepository="${REPO}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  create_pr:
    strategy:
      matrix:
        repo:
          - pagopa-ecommerce-transactions-service
          - pagopa-ecommerce-transactions-scheduler-service
          - pagopa-ecommerce-event-dispatcher-service
          - pagopa-ecommerce-payment-methods-service
          - pagopa-ecommerce-helpdesk-service
          - pagopa-ecommerce-helpdesk-commands-service
          - pagopa-ecommerce-cdc-service

    name: Create PR on ${{ matrix.repo }}
    runs-on: ubuntu-latest
    needs: deploy_artifact
    steps:
      - name: Get latest release tag from pagopa-ecommerce-commons
        id: get_latest_tag
        run: |
          git clone https://github.com/pagopa/pagopa-ecommerce-commons
          cd pagopa-ecommerce-commons
          latestTag=$(git describe --tags --abbrev=0)
          echo "Latest ecommerce-commons tag: $latestTag"
          echo "LATEST_TAG=$latestTag" >> $GITHUB_OUTPUT
        shell: bash

      - name: Checkout pagopa/${{ matrix.repo }}
        uses: actions/checkout@v3
        with:
          repository: pagopa/${{ matrix.repo }}

      - name: Replace old version with new version (Maven)
        uses: jacobtomlinson/gha-find-replace@a51bbcd94d000df9ca0fcb54ec8be69aad8374b0
        with:
          find: "<pagopa-ecommerce-commons.version>\\d+\\.\\d+\\.\\d+</pagopa-ecommerce-commons.version>"
          replace: "<pagopa-ecommerce-commons.version>${{ steps.get_latest_tag.outputs.LATEST_TAG }}</pagopa-ecommerce-commons.version>"
          regex: true
          include: "pom.xml"

      - name: Replace old version with new version (Gradle)
        uses: jacobtomlinson/gha-find-replace@a51bbcd94d000df9ca0fcb54ec8be69aad8374b0
        with:
          find: "val ecommerceCommonsVersion = \"\\d+\\.\\d+\\.\\d+\""
          replace: "val ecommerceCommonsVersion = \"${{ steps.get_latest_tag.outputs.LATEST_TAG }}\""
          regex: true
          include: "build.gradle.kts"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38
        with:
          branch: "update-commons-${{ steps.get_latest_tag.outputs.LATEST_TAG }}"
          token: ${{ secrets.PR_GITHUB_TOKEN }}
          author: pagopa-platform-github-bot <pagopa-github-bot@pagopa.it>
          committer: pagopa-platform-github-bot <pagopa-platform-github-bot@pagopa.it>
          commit-message: "chore(deps): update `commons` version to ${{ steps.get_latest_tag.outputs.LATEST_TAG }}"
          title: "chore(deps): update `commons` version to ${{ steps.get_latest_tag.outputs.LATEST_TAG }}"
          body: |
            <!--- Please always add a PR description as if nobody knows anything about the context these changes come from. -->
            <!--- Even if we are all from our internal team, we may not be on the same page. -->
            <!--- Write this PR as you were contributing to a public OSS project, where nobody knows you and you have to earn their trust. -->
            <!--- This will improve our projects in the long run! Thanks. -->
            
            #### List of Changes
            
            <!--- Describe your changes in detail -->
            * update `pagopa-ecommerce-commons` version to ${{ steps.get_latest_tag.outputs.LATEST_TAG }}
            
            #### Motivation and Context
            <!--- Why is this change required? What problem does it solve? -->
            Ordinary maintenance
            
            #### How Has This Been Tested?
            <!--- Please describe in detail how you tested your changes. -->
            <!--- Include details of your testing environment, tests ran to see how -->
            <!--- your change affects other areas of the code, etc. -->
            
            #### Types of changes
            
            <!--- What types of changes does your code introduce? Put an `x` in all the boxes that apply: -->
            
            - [ ] Bug fix (non-breaking change which fixes an issue)
            - [ ] New feature (non-breaking change which adds functionality)
            - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
            
            #### Checklist:
            
            <!--- Go over all the following points, and put an `x` in all the boxes that apply. -->
            <!--- If you're unsure about any of these, don't hesitate to ask. We're here to help! -->
            
            - [ ] My change requires a change to the documentation.
            - [ ] I have updated the documentation accordingly.
          labels: |
            🤖 automatic
            commons
            patch
            chart-patch
